### ISSUE TITLE
Exception issues when host doesnt respond properly

### ISSUE THREAD

**Issue by imerr** [fuel/email#54]
So, I might just be too stupid to handle this properly, but if I am stupid enough other people will be too.

I've got a little script to send emails:

``` PHP
$mail=Email::forge();
        $mail->subject($title);
        $mail->html_body(\View::forge('email/newsletter'));
        foreach ($emails as $email){
            $mail->to($email);
            try
            {
                $mail->send();
                echo $email." OK\n";
            }
            catch(Exception $e)
            {
                // The driver could not send the email
                echo $email." ERROR\n";
            }
            $mail->clear_recipients();
        }

```

So, this works out alright, it's not perfect but does the job.
Now i ran into an issue
It keeps throwing exceptions when it recieves an invalid response

```
Uncaught exception Email\SmtpCommandFailureException: Got an unexpected response from host on command: [QUIT] expecting: 221 received:
Callstack:
#0 /www/cyperia/cyperia.org/lib/packages/email/classes/email/driver/smtp.php(160): Email\Email_Driver_Smtp->smtp_send('QUIT', 221)
#1 /www/cyperia/cyperia.org/lib/packages/email/classes/email/driver/smtp.php(37): Email\Email_Driver_Smtp->smtp_disconnect()
#2 /www/cyperia/cyperia.org/lib/core/base.php(428): Email\Email_Driver_Smtp->__destruct()
#3 /www/cyperia/cyperia.org/lib/core/base.php(428): Fuel\Tasks\Newsletter->run()
#4 /www/cyperia/cyperia.org/lib/packages/oil/classes/refine.php(106): call_fuel_func_array(Array, Array)
#5 [internal function]: Oil\Refine::run('newsletter', Array)
#6 /www/cyperia/cyperia.org/lib/packages/oil/classes/command.php(125): call_user_func('Oil\Refine::run', 'newsletter', Array)
#7 /www/cyperia/cyperia.org/oil(57): Oil\Command::init(Array)
#8 {main}

Previous exception:
Uncaught exception Email\SmtpCommandFailureException: Got an unexpected response from host on command: [RCPT TO:<xxx@googlemail.de>] expecting: 250 or 251 received:
Callstack:
#0 /www/cyperia/cyperia.org/lib/packages/email/classes/email/driver/smtp.php(79): Email\Email_Driver_Smtp->smtp_send('RCPT TO:<balkow...', Array)
#1 /www/cyperia/cyperia.org/lib/packages/email/classes/email/driver.php(884): Email\Email_Driver_Smtp->_send()
#2 /www/cyperia/cyperia.org/app/tasks/newsletter.php(25): Email\Email_Driver->send()
#3 /www/cyperia/cyperia.org/lib/core/base.php(428): Fuel\Tasks\Newsletter->run()
#4 /www/cyperia/cyperia.org/lib/packages/oil/classes/refine.php(106): call_fuel_func_array(Array, Array)
#5 [internal function]: Oil\Refine::run('newsletter', Array)
#6 /www/cyperia/cyperia.org/lib/packages/oil/classes/command.php(125): call_user_func('Oil\Refine::run', 'newsletter', Array)
#7 /www/cyperia/cyperia.org/oil(57): Oil\Command::init(Array)
#8 {main}
```

And I cannot - for the life of me - seem to catch the second (top) exception which causes it to abort 

Any ideas as to what to do?
This really seems like a bug.. or issue of some sort.
It should probably terminate the connection when it recieves an empty response, right?

**Comment by imerr** [comment]
Nevermind.
Catching \Exception instead of just Exception seems to have done it..
